$(document).ready(function(){
  $("#owl-carousel").owlCarousel({
    items:1,
    dots:false,
    mouseDrag:false,
    touchDrag:false,
    loop:true,
    animateOut:'fadeOut',
    autoplay:true,
    autoplayTimeout:5000
  });
});